[debug] > Exec(run, None, None)
[debug] Evaluating tasks: Compile / run
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[error] java.io.FileNotFoundException: C:\Users\cakdeniz\Desktop\projects\java\spark-scala\target\scala-2.12\classes\WordCount$.class (The process cannot access the file because it is being used by another process)
[error] 	at java.io.FileInputStream.open0(Native Method)
[error] 	at java.io.FileInputStream.open(FileInputStream.java:195)
[error] 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[error] 	at sbt.io.Using$.$anonfun$fileInputStream$1(Using.scala:99)
[error] 	at sbt.io.Using$$anon$3.openImpl(Using.scala:87)
[error] 	at sbt.io.OpenFile.open(Using.scala:54)
[error] 	at sbt.io.OpenFile.open$(Using.scala:48)
[error] 	at sbt.io.Using$$anon$3.open(Using.scala:86)
[error] 	at sbt.io.Using$$anon$3.open(Using.scala:86)
[error] 	at sbt.io.Using.apply(Using.scala:26)
[error] 	at sbt.io.IO$.transfer(IO.scala:454)
[error] 	at sbt.io.IO$.addFileEntry$1(IO.scala:718)
[error] 	at sbt.io.IO$.$anonfun$writeZip$6(IO.scala:726)
[error] 	at sbt.io.IO$.$anonfun$writeZip$6$adapted(IO.scala:726)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at sbt.io.IO$.writeZip(IO.scala:726)
[error] 	at sbt.io.IO$.$anonfun$archive$2(IO.scala:676)
[error] 	at sbt.io.IO$.$anonfun$archive$2$adapted(IO.scala:673)
[error] 	at sbt.io.IO$.$anonfun$withZipOutput$1(IO.scala:773)
[error] 	at sbt.io.IO$.$anonfun$withZipOutput$1$adapted(IO.scala:753)
[error] 	at sbt.io.Using.apply(Using.scala:28)
[error] 	at sbt.io.IO$.withZipOutput(IO.scala:753)
[error] 	at sbt.io.IO$.archive(IO.scala:673)
[error] 	at sbt.io.IO$.jar(IO.scala:638)
[error] 	at sbt.Package$.makeJar(Package.scala:229)
[error] 	at sbt.Package$.$anonfun$apply$4(Package.scala:152)
[error] 	at sbt.Package$.$anonfun$apply$4$adapted(Package.scala:150)
[error] 	at sbt.util.Tracked$.$anonfun$outputChangedW$1(Tracked.scala:129)
[error] 	at sbt.Package$.apply(Package.scala:162)
[error] 	at sbt.Defaults$.$anonfun$packageTask$1(Defaults.scala:1868)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:750)
[error] (Compile / packageBin) java.io.FileNotFoundException: C:\Users\cakdeniz\Desktop\projects\java\spark-scala\target\scala-2.12\classes\WordCount$.class (The process cannot access the file because it is being used by another process)
[error] Total time: 7 s, completed 09.Oca.2024 15:40:43
[debug] > Exec(idea-shell, None, None)
[debug] > Exec(, None, None)
[debug] > Exec(idea-shell, None, None)
